name: Run Tests

on:
    pull_request:
       types: [opened, synchronize]

concurrency:
    group: flutter-tests-${{ github.ref }}
    cancel-in-progress: true

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emulator
        uses: futureware-tech/simulator-action@v3
        with:
           model: 'iPhone 15'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
            sdk: '3.7.0'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
           channel: stable
           architecture: x64
           flutter-version: '3.29.1'

      - name: Create .env file
        run: |
            cat <<EOF > .env
            MAPBOX_ACCESS_TOKEN=token
            SENTRY_DSN=dsn
            KEYSTORE_FILE=path
            KEYSTORE_PASSWORD=password
            KEY_ALIAS=alias
            KEY_PASSWORD=password
            EOF

      - name: Run tests
        run: flutter test